[package]
name = "volume-inspector"
version = "0.1.1"
edition = "2024"

[dependencies]
ratatui = "0.28.1"        # обновляем до свежей версии
crossterm = "0.27"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
humansize = "2.1"
seahash = "4.1"
once_cell = "1.19"